### ISSUE TITLE
Request to get Unlock Instructions rejected

### ISSUE THREAD

**Issue by yarunluon** [fnf-org/TicketBooth#145]
I do not know what unlock instructions are, but I thought I would explore this link, because it was available. If Unlock Instructions are not part of any flow, maybe we should hide the link. 

**Describe the bug**
After submitting request to get Unlock instructions, I am shown a system message saying my request was rejected. 

Possibly related log:  
https://onenr.io/0BR67ZnbbjO

**To Reproduce**
1. Go to: https://tickets.fnf.events/users/unlock/new
2. Enter email address and submit request
3. See rejection message

**Expected behavior**
Unlock instructions are successfully sent to the user with a value email address

**Screenshots**
![rejected-unlock-instructions](https://github.com/fnf-org/TicketBooth/assets/1328337/77ef19cf-8fa4-4d3a-b2b7-2f7573ed1a2e)

**Version info**  
App Version: `1.0.1`  
Rails: `7.1.3.2`  
Ruby: `3.2.3`  
Mode: `production`

**Comment by beingmattlevy** [comment]
Fixed language. Links working.

**Comment by yarunluon** [comment]
i can confirm the copy was changed, but the behavior is still the same. I am presented with a rejection screen. See SS. Is it a requirement that the account needs to be locked out for the Unlock instructions to be sent?

![rejected-unlock-instructions-2024-05-13](https://github.com/fnf-org/TicketBooth/assets/1328337/3f0d9244-8e8e-4684-a837-a9234596ffc2)

**Comment by kigster** [comment]
I can fix this. The issue is with CSRF token.

@yarunluon The library we use "Devise" has a feature that automatically "locks" accounts after 10 consecutive failed login attempts. The email link unlocks it.

**Comment by beingmattlevy** [comment]
This is working. Attempt login 10 times with bad password. 
Click link to unlock the frozen account. 
It works. Not sure why the error is not showing up though

**Comment by yarunluon** [comment]
Thanks for explaining. Can confirm. Lockout does work when the account is locked out. The Rejection message only displays when the account is not locked out.

**Comment by yarunluon** [comment]
I don't know if anything needs fixing. It would be nice to display a message like "If your account is locked out, we'll send you Lockout instructions", but that work is beyond the scope of this ticket.

**Comment by yarunluon** [comment]
Ill leave it up you to close this ticket.
